// Fitness content for the building community page.
// Images use Unsplash CDN; app.js applies a gradient fallback if a photo fails.

window.BUILDING_GYMS = [
  {
    id: "building-fitness",
    name: "Building Fitness Center",
    category: "In-building gym",
    location: "Level B1 · Resident amenity",
    hours: "Open 24/7 with key fob",
    address: "Main Lobby, Level B1",
    distance: "Inside your building",
    rating: 4.9,
    reviews: 186,
    free: true,
    img: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=70",
    fallback: "strength",
    tagline: "Strength floor, cardio theater, and free weights — complimentary for residents.",
    perks: ["Free for residents", "24/7 access", "Locker rooms & showers", "Towels provided"],
  },
  {
    id: "rooftop-wellness",
    name: "Rooftop Wellness Studio",
    category: "In-building studio",
    location: "Floor 32 · Sky Lounge",
    hours: "5:00 AM – 10:00 PM daily",
    address: "Floor 32 Sky Lounge",
    distance: "Inside your building",
    rating: 4.8,
    reviews: 94,
    free: true,
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=70",
    fallback: "yoga",
    tagline: "Light-filled studio for yoga, mobility, and recovery — free signup for residents.",
    perks: ["Free for residents", "Mats & props on site", "City skyline views", "Quiet recovery zone"],
  },
];

window.GYMS = [
  {
    id: "orangetheory",
    name: "Orangetheory Fitness",
    category: "Heart-rate interval training",
    tags: ["strength", "popular"],
    badges: [{ type: "popular", label: "Popular" }],
    address: "441 North Wells Street, Chicago, IL 60654",
    distance: "0.3 mi from Main Lobby",
    rating: 4.7,
    reviews: 389,
    img: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "Coach-led HIIT built around live heart-rate zones.",
  },
  {
    id: "corepower",
    name: "CorePower Yoga",
    category: "Heated yoga & sculpt",
    tags: ["yoga", "new"],
    badges: [{ type: "new", label: "New near you" }],
    address: "700 North Milwaukee Ave, Chicago, IL 60642",
    distance: "0.5 mi from Main Lobby",
    rating: 4.6,
    reviews: 274,
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=70",
    fallback: "yoga",
    tagline: "Vinyasa, hot power fusion & yoga sculpt classes.",
  },
  {
    id: "barrys",
    name: "Barry's",
    category: "Strength + cardio bootcamp",
    tags: ["strength", "popular", "limited"],
    badges: [{ type: "popular", label: "Popular" }, { type: "limited", label: "Limited spots" }],
    address: "1 East Erie Street, Chicago, IL 60611",
    distance: "0.4 mi from Main Lobby",
    rating: 4.9,
    reviews: 631,
    img: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "The original strength & cardio Red Room workout.",
  },
  {
    id: "soulcycle",
    name: "SoulCycle",
    category: "Indoor cycling studio",
    tags: ["cycle", "popular"],
    badges: [{ type: "popular", label: "Popular" }],
    address: "217 North Jefferson Street, Chicago, IL 60661",
    distance: "0.6 mi from Main Lobby",
    rating: 4.7,
    reviews: 448,
    img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    fallback: "cycle",
    tagline: "Rhythm-based indoor cycling in a candlelit studio.",
  },
  {
    id: "titleboxing",
    name: "TITLE Boxing Club",
    category: "Boxing & kickboxing",
    tags: ["boxing", "new"],
    badges: [{ type: "new", label: "New near you" }],
    address: "1516 North Wells Street, Chicago, IL 60610",
    distance: "0.8 mi from Main Lobby",
    rating: 4.5,
    reviews: 196,
    img: "https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=800&q=70",
    fallback: "boxing",
    tagline: "Heavy-bag boxing & kickboxing power hours.",
  },
  {
    id: "solidcore",
    name: "[solidcore]",
    category: "Pilates-inspired strength",
    tags: ["yoga", "new", "limited"],
    badges: [{ type: "new", label: "New near you" }, { type: "limited", label: "Limited spots" }],
    address: "18 West Hubbard Street, Chicago, IL 60654",
    distance: "0.2 mi from Main Lobby",
    rating: 4.9,
    reviews: 357,
    img: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=70",
    fallback: "yoga",
    tagline: "50 minutes of slow, controlled, full-body strength.",
  },
];

// Fitness events — dates are generated relative to today in app.js via `offsetDays`.
window.EVENT_TEMPLATES = [
  {
    id: "sunrise-yoga",
    title: "Sunrise Yoga",
    type: "yoga",
    place: "Rooftop Wellness Studio",
    time: "6:30 AM – 7:30 AM",
    spots: 18,
    offsetDays: 0,
    description: "Gentle flow to start the day with skyline views.",
  },
  {
    id: "hiit-bootcamp",
    title: "Lobby HIIT Bootcamp",
    type: "strength",
    place: "Building Fitness Center",
    time: "12:00 PM – 12:45 PM",
    spots: 12,
    offsetDays: 0,
    description: "Express lunch-break intervals — bring sneakers.",
  },
  {
    id: "mobility-reset",
    title: "Mobility Reset",
    type: "recovery",
    place: "Rooftop Wellness Studio",
    time: "6:00 PM – 6:45 PM",
    spots: 16,
    offsetDays: 1,
    description: "Hip openers, foam rolling, and breathwork.",
  },
  {
    id: "strength-circuit",
    title: "Resident Strength Circuit",
    type: "strength",
    place: "Building Fitness Center",
    time: "7:00 AM – 8:00 AM",
    spots: 14,
    offsetDays: 2,
    description: "Coach-led full-body circuit for all levels.",
  },
  {
    id: "pilates-core",
    title: "Core & Pilates",
    type: "yoga",
    place: "Rooftop Wellness Studio",
    time: "5:30 PM – 6:30 PM",
    spots: 20,
    offsetDays: 3,
    description: "Mat pilates focused on core control and posture.",
  },
  {
    id: "boxing-basics",
    title: "Boxing Basics",
    type: "boxing",
    place: "Building Fitness Center",
    time: "6:30 PM – 7:30 PM",
    spots: 10,
    offsetDays: 4,
    description: "Footwork, jab-cross drills, and bag work.",
  },
  {
    id: "weekend-run",
    title: "Neighborhood Fun Run",
    type: "cardio",
    place: "Meet at Main Lobby",
    time: "8:00 AM – 9:00 AM",
    spots: 30,
    offsetDays: 5,
    description: "Easy 3-mile loop with the resident run club.",
  },
  {
    id: "sound-bath",
    title: "Evening Sound Bath",
    type: "recovery",
    place: "Rooftop Wellness Studio",
    time: "7:30 PM – 8:30 PM",
    spots: 22,
    offsetDays: 6,
    description: "Guided rest with singing bowls — mats provided.",
  },
  {
    id: "power-yoga",
    title: "Power Yoga",
    type: "yoga",
    place: "Rooftop Wellness Studio",
    time: "6:00 AM – 7:00 AM",
    spots: 18,
    offsetDays: 8,
    description: "Energizing vinyasa for intermediate movers.",
  },
  {
    id: "family-fit",
    title: "Family Fit Saturday",
    type: "cardio",
    place: "Building Fitness Center",
    time: "10:00 AM – 11:00 AM",
    spots: 24,
    offsetDays: 9,
    description: "Kid-friendly movement games and light cardio.",
  },
  {
    id: "kettlebell",
    title: "Kettlebell Clinic",
    type: "strength",
    place: "Building Fitness Center",
    time: "5:00 PM – 6:00 PM",
    spots: 12,
    offsetDays: 11,
    description: "Form-focused swings, cleans, and presses.",
  },
  {
    id: "stretch-social",
    title: "Stretch & Social",
    type: "recovery",
    place: "Rooftop Wellness Studio",
    time: "6:00 PM – 7:00 PM",
    spots: 20,
    offsetDays: 13,
    description: "Long holds plus a light community mixer after.",
  },
];
