// Fitness partners near the building. Images use Unsplash CDN with a
// gradient fallback (see app.js) so the page never renders broken tiles.
window.GYMS = [
  {
    id: "vantage",
    name: "Vantage Athletic Club",
    category: "Full-service athletic club",
    tags: ["strength", "new"],
    badges: [{ type: "new", label: "New offer" }],
    address: "360 West Hubbard Street, Chicago, IL 60654",
    distance: "0.2 mi from Main Lobby",
    rating: 4.8, reviews: 512,
    priceFrom: 89,
    img: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "Lap pool, strength floor, group fitness & recovery spa.",
    tiers: [
      { id: "day", name: "Day Pass", note: "Single visit, all facilities", price: 25, unit: "one-time" },
      { id: "monthly", name: "Monthly", note: "Unlimited access, no contract", price: 89, unit: "/mo", tag: "Popular" },
      { id: "annual", name: "Annual", note: "12 months · 2 months free", price: 890, unit: "/yr" },
    ],
  },
  {
    id: "orangetheory",
    name: "Orangetheory Fitness",
    category: "Heart-rate interval training",
    tags: ["strength", "popular"],
    badges: [{ type: "popular", label: "Popular" }],
    address: "441 North Wells Street, Chicago, IL 60654",
    distance: "0.3 mi from Main Lobby",
    rating: 4.7, reviews: 389,
    priceFrom: 79,
    img: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "Coach-led HIIT built around live heart-rate zones.",
    tiers: [
      { id: "intro", name: "First Class", note: "Intro session for new members", price: 0, unit: "free", tag: "Free" },
      { id: "basic", name: "Basic (4/mo)", note: "4 classes each month", price: 79, unit: "/mo" },
      { id: "elite", name: "Elite", note: "8 classes each month", price: 119, unit: "/mo", tag: "Popular" },
      { id: "premier", name: "Premier", note: "Unlimited classes", price: 179, unit: "/mo" },
    ],
  },
  {
    id: "corepower",
    name: "CorePower Yoga",
    category: "Heated yoga & sculpt",
    tags: ["yoga", "new"],
    badges: [{ type: "new", label: "New offer" }],
    address: "700 North Milwaukee Ave, Chicago, IL 60642",
    distance: "0.5 mi from Main Lobby",
    rating: 4.6, reviews: 274,
    priceFrom: 99,
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=70",
    fallback: "yoga",
    tagline: "Vinyasa, hot power fusion & yoga sculpt classes.",
    tiers: [
      { id: "week", name: "Free Week", note: "7 days unlimited, new members", price: 0, unit: "free", tag: "Free" },
      { id: "monthly", name: "Monthly", note: "Unlimited studio classes", price: 99, unit: "/mo", tag: "Popular" },
      { id: "annual", name: "Annual", note: "Best value · billed yearly", price: 990, unit: "/yr" },
    ],
  },
  {
    id: "barrys",
    name: "Barry's",
    category: "Strength + cardio bootcamp",
    tags: ["strength", "popular", "limited"],
    badges: [{ type: "popular", label: "Popular" }, { type: "limited", label: "Limited spots" }],
    address: "1 East Erie Street, Chicago, IL 60611",
    distance: "0.4 mi from Main Lobby",
    rating: 4.9, reviews: 631,
    priceFrom: 38,
    img: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "The original strength & cardio Red Room workout.",
    tiers: [
      { id: "single", name: "Single Class", note: "Drop-in", price: 38, unit: "one-time" },
      { id: "pack", name: "10-Class Pack", note: "Save 15% vs. drop-in", price: 320, unit: "pack", tag: "Best value" },
      { id: "unlimited", name: "Unlimited", note: "Unlimited monthly classes", price: 285, unit: "/mo" },
    ],
  },
  {
    id: "soulcycle",
    name: "SoulCycle",
    category: "Indoor cycling studio",
    tags: ["cycle", "popular"],
    badges: [{ type: "popular", label: "Popular" }],
    address: "217 North Jefferson Street, Chicago, IL 60661",
    distance: "0.6 mi from Main Lobby",
    rating: 4.7, reviews: 448,
    priceFrom: 34,
    img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    fallback: "cycle",
    tagline: "Rhythm-based indoor cycling in a candlelit studio.",
    tiers: [
      { id: "single", name: "Single Ride", note: "Drop-in class", price: 34, unit: "one-time" },
      { id: "series", name: "5-Ride Series", note: "Expires in 30 days", price: 160, unit: "pack" },
      { id: "monthly", name: "Monthly Unlimited", note: "Ride as much as you want", price: 250, unit: "/mo", tag: "Popular" },
    ],
  },
  {
    id: "titleboxing",
    name: "TITLE Boxing Club",
    category: "Boxing & kickboxing",
    tags: ["boxing", "new"],
    badges: [{ type: "new", label: "New offer" }],
    address: "1516 North Wells Street, Chicago, IL 60610",
    distance: "0.8 mi from Main Lobby",
    rating: 4.5, reviews: 196,
    priceFrom: 69,
    img: "https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=800&q=70",
    fallback: "boxing",
    tagline: "Heavy-bag boxing & kickboxing power hours.",
    tiers: [
      { id: "intro", name: "First Class", note: "Free intro with gloves", price: 0, unit: "free", tag: "Free" },
      { id: "basic", name: "Basic (8/mo)", note: "8 classes monthly", price: 69, unit: "/mo" },
      { id: "unlimited", name: "Unlimited", note: "Unlimited monthly classes", price: 109, unit: "/mo", tag: "Popular" },
    ],
  },
  {
    id: "equinox",
    name: "Equinox River North",
    category: "Luxury fitness club",
    tags: ["strength", "yoga", "limited"],
    badges: [{ type: "limited", label: "Limited spots" }],
    address: "200 West Monroe Street, Chicago, IL 60606",
    distance: "0.7 mi from Main Lobby",
    rating: 4.8, reviews: 823,
    priceFrom: 215,
    img: "https://images.unsplash.com/photo-1637666505879-6cbea6f79e6b?auto=format&fit=crop&w=800&q=70",
    fallback: "strength",
    tagline: "Premium clubs, studio classes, spa & personal training.",
    tiers: [
      { id: "monthly", name: "All-Access", note: "Single-club membership", price: 215, unit: "/mo", tag: "Popular" },
      { id: "destination", name: "Destination", note: "Access all clubs nationwide", price: 305, unit: "/mo" },
    ],
  },
  {
    id: "solidcore",
    name: "[solidcore]",
    category: "Pilates-inspired strength",
    tags: ["yoga", "new", "limited"],
    badges: [{ type: "new", label: "New offer" }, { type: "limited", label: "Limited spots" }],
    address: "18 West Hubbard Street, Chicago, IL 60654",
    distance: "0.2 mi from Main Lobby",
    rating: 4.9, reviews: 357,
    priceFrom: 42,
    img: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=70",
    fallback: "yoga",
    tagline: "50 minutes of slow, controlled, full-body strength.",
    tiers: [
      { id: "single", name: "Single Class", note: "Drop-in", price: 42, unit: "one-time" },
      { id: "pack", name: "4-Class Pack", note: "Great to get started", price: 152, unit: "pack" },
      { id: "unlimited", name: "Unlimited", note: "Unlimited monthly classes", price: 269, unit: "/mo", tag: "Popular" },
    ],
  },
];
